#+title: Data package for 'Laser-induced surface modification of C/PEKK for co-bonding with C/epoxy'
#+date: 2026-01-01
#+options: num:0 toc:nil author:nil

* General information

Insert generic information, e.g. a reference to the publication that the data belong to.

This dataset contains:
- Add contents


** Authors & Affiliations

- Ivaylo Lazarov, University of Twente
- Liran Katz, ThermoPlastic composites Research Center
- Joran Geschiere, ThermoPlastic composites Research Center
- Nick Helthuis, University of Twente
- Wouter Grouve, University of Twente

** Correspondence

- Wouter Grouve (w.j.b.grouve@utwente.nl)

** License

The journal article as well as this dataset are published under a CC BY license. See `LICENSE.txt` file in this repository.

** Citation

In case you use this data, please cite the original article:

#+BEGIN_SRC bibtex :tangle CITATION.bib
@article{bibkey,
  author    = {},
  title     = {},
  journal   = {},
  year      = {},
  volume    = {},
  month     = {},
  pages     = {},
  issn      = {},
  publisher = {}}
#+END_SRC

as well as this dataset:

#+BEGIN_SRC bibtex :tangle CITATION.bib
@article{bibkey_data,
  author    = {$4},
  title     = {$1},
  year      = ${8:`(format-time-string "%Y")`},
  doi       = ${9:FIXME doi},
  publisher = ${10:4TU.ResearchData},
  copyright = {$7}}
#+END_SRC

** Funding and acknowledgments

Add funding information and acknowledgements.

* Dataset

The measured data is organized in the following folders:
-


** Measurement #1

Briefly describe where the data can be found, the file naming convention used, and how the files themselves are structures.

** Measurement #2

Briefly describe where the data can be found, the file naming convention used, and how the files themselves are structures.

* Code

Mention which software (including version) was used to analyze the data and that the scripts can be found in the folder `code`.

# Local Variables:
# eval: (add-hook 'after-save-hook
#                 (lambda ()
#                 (org-babel-tangle)
#                 (org-ascii-export-to-ascii))
#               nil t)
# End:
